name: deploy-demo

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - run: echo "Deploying to staging"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - run: echo "Deploying to production"
